/*
 * Corbin Nash
 * 21/03/2018
 * This program calculatees a 10% discount on a sale above ten dollars
 */

package ics3u_unit2_programs_sale;
import java.text.DecimalFormat;
/**
 *
 * @author conas1290
 */
public class ICS3U_UNIT2_PROGRAMS_Sale extends javax.swing.JFrame {

    /**
     * Creates new form ICS3U_UNIT2_PROGRAMS_Sale
     */
    public ICS3U_UNIT2_PROGRAMS_Sale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        superStoreSaleLabel = new javax.swing.JLabel();
        amountPurchases = new javax.swing.JLabel();
        discountAmount = new javax.swing.JLabel();
        discountPrice = new javax.swing.JLabel();
        caluculateButton = new javax.swing.JButton();
        purchacesOutput = new javax.swing.JTextField();
        discountAmountLabel = new javax.swing.JLabel();
        discountPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        superStoreSaleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        superStoreSaleLabel.setText("$uper $tore $ale");

        amountPurchases.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountPurchases.setText("Amount Of Purchases:");

        discountAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        discountAmount.setText("Discount Amount:");

        discountPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        discountPrice.setText("Discount Price:");

        caluculateButton.setText("Calculate!!!");
        caluculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caluculateButtonActionPerformed(evt);
            }
        });

        purchacesOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchacesOutputActionPerformed(evt);
            }
        });

        discountAmountLabel.setText("Discount goes here");

        discountPriceLabel.setText("Final price goes here");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(superStoreSaleLabel))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(amountPurchases)
                            .addComponent(discountAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discountPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(discountAmountLabel))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(discountPriceLabel)
                                    .addComponent(purchacesOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(caluculateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(superStoreSaleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountPurchases)
                    .addComponent(purchacesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caluculateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountAmount)
                    .addComponent(discountAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountPrice)
                    .addComponent(discountPriceLabel))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchacesOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchacesOutputActionPerformed

    }//GEN-LAST:event_purchacesOutputActionPerformed

    private void caluculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caluculateButtonActionPerformed
        double dAmount, dPrice, aPurchase ;
        DecimalFormat x = new DecimalFormat ("########.##");
        aPurchase = Double.parseDouble(purchacesOutput.getText()) ; //Grabs from the first input
  
        if (aPurchase > 10) 
        {
            dAmount = aPurchase*0.10; //gets 10% of the purchase made
        }
        else dAmount = 0;
        
           dPrice = aPurchase-dAmount; //Calculates final price
          discountAmountLabel.setText(x.format(dAmount));
          discountPriceLabel.setText(x.format(dPrice));
    }//GEN-LAST:event_caluculateButtonActionPerformed
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ICS3U_UNIT2_PROGRAMS_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ICS3U_UNIT2_PROGRAMS_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ICS3U_UNIT2_PROGRAMS_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ICS3U_UNIT2_PROGRAMS_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ICS3U_UNIT2_PROGRAMS_Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPurchases;
    private javax.swing.JButton caluculateButton;
    private javax.swing.JLabel discountAmount;
    private javax.swing.JLabel discountAmountLabel;
    private javax.swing.JLabel discountPrice;
    private javax.swing.JLabel discountPriceLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField purchacesOutput;
    private javax.swing.JLabel superStoreSaleLabel;
    // End of variables declaration//GEN-END:variables
}
